samplesheet:       "docs/samplesheet.csv"
transcriptome_url: "http://ftp.ensembl.org/pub/release-106/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz"
fast5_dir:         "/data/raw"

containers:
  nanocompore:        "library://aleg/default/nanocompore:1.0.3"
  metacompore_python: "library://aleg/default/metacompore_python:3.8.6"
  # f5c:                "docker://quay.io/mbhall88/f5c-gpu:0.6"
  f5c:                "library://aleg/default/f5c:cpu-0.6" 
  pybiotools:         "library://aleg/default/pybiotools:0.2.7"
  guppy:              "docker://quay.io/mbhall88/guppy-gpu:5.0.16"
  xpore:              "docker://quay.io/biocontainers/xpore:2.1--pyh5e36f6f_0"
  base:               "docker://bash:5.1"
